name: Run Dagger Example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Dagger Module
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: 0.18.6
          verb: call
          module: not-working
          args: |
            say-hello
