name: Run Dagger Example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.LOCAL_DAG_DEPLOY_KEY }}

      - name: Run Dagger Module
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: v0.18.14
          verb: call
          module: git@github.com:JCastillo07/dagger_example.git/not-working@main
          args: say-hello